# Generated by Django 5.1.5 on 2025-02-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_comment_bid_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(default='undefined', max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
